### ISSUE TITLE
golang矩阵转置

### ISSUE THREAD

**Issue by fuchao01** [chfenger/goNum#2]
你好，请问golang做矩阵转置有什么思路吗？例如：4维矩阵，0和2维做转置

**Comment by chfenger** [comment]
目前没有思路，而且记得只有向量和二维矩阵可以做转置吧？

**Comment by chfenger** [comment]
> 
> 
> 你好，请问golang做矩阵转置有什么思路吗？例如：4维矩阵，0和2维做转置

目前没有思路，而且记得只有向量和二维矩阵可以做转置吧？
